services:
  frontend:
    image: bkirilov/santase_frontend:latest
    container_name: santase_frontend
    restart: always
    environment:
      - TZ=Europe/Sofia
    networks:
      - santase_network

  backend:
    image: ${DOCKERHUB_USERNAME}/santase_backend:latest
    container_name: santase_backend
    restart: always
    env_file: .env
    volumes:
      - /home/ubuntu/app/backend_logs:/app/logs
    environment:
      - TZ=Europe/Sofia
      - JAVA_OPTS=-Duser.timezone=Europe/Sofia
    networks:
      - santase_network

networks:
  santase_network:
    driver: bridge