services:
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - santase_network

  frontend:
    image: bkirilov/santase_frontend:latest
    container_name: santase_frontend
    restart: always
    # No ports exposed! The main nginx proxy handles external traffic.
    networks:
      - santase_network

  backend:
    image: ${DOCKERHUB_USERNAME}/santase_backend:latest
    container_name: santase_backend
    restart: always
    env_file: .env
    networks:
      - santase_network

networks:
  santase_network:
    driver: bridge