worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    limit_req_log_level notice;

    limit_req_zone $binary_remote_addr zone=auth_limit:10m rate=10r/m;
    limit_req_zone $binary_remote_addr zone=game_limit:10m rate=30r/m;
    limit_req_zone $binary_remote_addr zone=user_limit:10m rate=10r/m;
    limit_conn_zone $binary_remote_addr zone=addr_limit:10m;
    limit_req_status 429;

    # 1. HTTP -> HTTPS Redirect
    server {
        listen 80;
        server_name deck.bg www.deck.bg;
        return 301 https://$host$request_uri;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name deck.bg www.deck.bg;

        ssl_certificate /etc/nginx/ssl/cloudflare-deck.crt;
        ssl_certificate_key /etc/nginx/ssl/cloudflare-deck.key;

        # Сигурност за SSL
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # Глобални хедъри за проксиране
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Frontend
        location / {
            proxy_pass http://frontend:80;
        }

        # Auth API с лимит 10r/m
        location /api/auth/ {
            limit_req zone=auth_limit burst=5 nodelay;
            proxy_pass http://backend:8080/auth/;
        }

        # Game API
        location /api/game/ {
            limit_req zone=game_limit burst=10 nodelay;
            proxy_pass http://backend:8080/game/;
            proxy_set_header Authorization $http_authorization;
        }

        # User API
        location /api/user/ {
            limit_req zone=user_limit burst=5 nodelay;
            proxy_pass http://backend:8080/user/;
            proxy_set_header Authorization $http_authorization;
        }

        # WebSocket
        location /api/ws-game/ {
            proxy_pass http://backend:8080/ws-game/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
        }
    }
}