spring:
  application:
    name: SantaseService

  datasource:
    url: jdbc:postgresql://localhost:5432/santase
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: ${DB_DIALECT}
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  secret-key: ${JWT_SECRET}
        # 15 minutes in milliseconds
  expiration: ${JWT_EXPIRATION}
        # 7 days in milliseconds
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}